### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by ermkmandawar** [SongTube/SongTube-App#49] opened 2021-03-09 09:14 UTC
Add an feature for run app in background. Like youtube premium

**Comment by Artx-II** [comment] 2021-03-09 13:22
How exactly in background?

**Comment by SanOtaku09** [comment] 2021-03-11 07:33
Like music player

**Comment by Artx-II** [comment] 2021-03-12 19:57
Then this is a duplicate of #31. Feel free to post any other comment about this on that issue 👍

**Closed by Artx-II** 2021-03-12 19:57 UTC
