### ISSUE TITLE
Feature Request: Add Support for SponsorBlock

### ISSUE THREAD

**Issue by ardrag0n** [SongTube/SongTube-App#236] opened 2023-09-02 12:01 UTC
### Describe your suggested feature

Sponsorblock is a great feature. It saves so much time. You should consider to add it to the app.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment] 2023-09-05 14:13
Duplicate of #103

This feature would take some time and it only hurts content creators, consider skipping the in-video sponsor or chapter (SongTube supports video chapters)

**Closed by Artx-II** 2023-09-05 14:13 UTC
