### ISSUE TITLE
Turkish font issue

### ISSUE THREAD

**Issue by muhaaliss** [SongTube/SongTube-App#181] opened 2022-05-09 14:53 UTC
![IMG_20220509_175248](https://user-images.githubusercontent.com/102979224/167437010-aca01afb-cdd2-4735-ac25-f1c077095c96.jpg)
#
![IMG_20220509_175225](https://user-images.githubusercontent.com/102979224/167437018-22f8a13d-64fe-4c99-b073-83c17feaa8b0.jpg)

**Comment by Artx-II** [comment] 2024-01-05 02:08
I cannot reproduce this issue by now.

It is unclear how the issue got fixed but I will close this anyways. If it persists please open this again.

**Closed by Artx-II** 2024-01-05 02:08 UTC
