### ISSUE TITLE
Put translation strings on Crowdin

### ISSUE THREAD

**Issue by nadiration** [SongTube/SongTube-App#44] opened 2021-02-08 18:47 UTC
The current translation process can be much better and easier for translators if you put it on [Crowdin](crowdin.com) which is free for open source apps anyway. By doing so it will be easier for everyone to translate, maintain and update as contrubutors get alerts when new strings are added/changed and it's really the user friendly localization platform with mobile view support for translating on the go.

**Comment by RickyM7** [comment] 2021-02-09 15:17
Basically a duplicate of #14.

**Comment by comradekingu** [comment] 2021-02-26 23:53
@nadiration Crowdin isn't gratis for open source. It only doesn't charge non-commercial projects, and it monetizes use by way of all sorts of scripts. Hosted or self-hosted Weblate qualifies for what you describe.

**Comment by Artx-II** [comment] 2021-09-27 19:43
Closing this since there is still no plans for putting translation strings on Crowdin and I'm considering other options.

If you guys would like to discuss about which option would be the best for translations please open a new issue for that.

**Closed by Artx-II** 2021-09-27 19:43 UTC
