### ISSUE TITLE
[Bug] tag editing not working 

### ISSUE THREAD

**Issue by Chen1Plus** [SongTube/SongTube-App#216] opened 2023-06-29 12:45 UTC
### Steps to reproduce

1. Download a song
2. Long press to trigger options
3. Choose tag editing option
4. Search for tag and click apply

### Expected behavior

Tag changed

### Actual behavior

The editing popup disappear but new tag was not applied. 

### SongTube version

7.0.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MrConqueror** [comment] 2023-07-03 00:22
yeah same but look, the results is always like this. I've been reporting this but the mods seems to be ignoring it
![Screenshot_2023-07-03-08-08-00-817_com artxdev songtube-edit](https://github.com/SongTube/SongTube-App/assets/102837820/5b538eb2-ff35-4896-91cf-f8cedb34b40a)

**Comment by Artx-II** [comment] 2023-07-05 00:34
The tag editor is working unexpectedly a lot of times, I've investigated and it seems that the problem is a bit more complicated than I expected, hence why I released a new update without fixing this.

That said, this issue is now on high priority, meaning next update is gonna have this problem fixed.

**Comment by Artx-II** [comment] 2023-09-07 03:36
Fixed with commit bcfbdbf

**Closed** 2023-09-07 03:37 UTC
Labels: bug
